version: "3.9"
services:
  liferay:
    image: liferay/dxp:2023.q4.4
    ports:
      - 8080:8080
    volumes:
      - ./liferay/files:/mnt/liferay/files
      - liferay_data:/opt/liferay/data
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  txtai:
    build:
      dockerfile: Dockerfile
      context: txtai
    ports:
      - 8000:8000
  elasticsearch:
    build:
      dockerfile: elasticsearch/Dockerfile
      context: .
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
     - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
  database:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: lportal
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

volumes:
  liferay_data:
  elasticsearch_data:
  database_data:
